version: '3'

services:
    djangoapp:
        restart: unless-stopped
        image: agmp
        container_name: agmp_instance
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        #`command: tail -f /dev/null
        volumes:
            - .:/agp
        ports:
            - 8008:8000
        networks:  # <-- here
        - nginx_network
    
    nginx:
        restart: unless-stopped
        image: nginx:1.13
        container_name: agmp_nginx_instance
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8000:80
        depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
            - djangoapp
        networks:  # <-- here
            - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
