# Generated by Django 2.2.24 on 2023-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='categories',
            field=models.ManyToManyField(to='core.Category'),
        ),
    ]
