# First, we declare our upstream Gunicorn server
upstream gunicorn_server {
    # Docker will automatically resolve this to the correct address
    # because we use the same name as the service: "djangoapp"
    server djangoapp:8000;
}

# Now we declare our main server
server {

    listen 80;
    server_name localhost;

    # Serve static files
    location /static/ {
        alias /agmp/static_cdn/;
    }

    # Serve media files (uploads)
    location /uploads/ {
        alias /agmp/uploads/;  # This should match MEDIA_ROOT in Django settings.py
        autoindex on;
        expires 30d;
        access_log off;
    }

    # Everything else is passed to Gunicorn
    location / {
        proxy_pass http://gunicorn_server;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
