# Generated by Django 2.2.1 on 2020-02-23 12:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.CharField(default='DRUG0', max_length=50, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250)),
                ('drug_bank_id', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
                ('indication', models.TextField()),
                ('iupac_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recname', models.CharField(max_length=250)),
                ('keywords', models.CharField(default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacogenes',
            fields=[
                ('id', models.CharField(default='GENE0', max_length=50, primary_key=True, serialize=False)),
                ('chromosome_patch', models.CharField(default='NA', max_length=50)),
                ('gene_name', models.CharField(default='NA', max_length=50)),
                ('uniprot_id', models.CharField(max_length=50, null=True)),
                ('function', models.TextField(default='NA', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=250)),
                ('year', models.CharField(default='NA', max_length=10)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='star_allele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('star_id', models.CharField(default='NA', max_length=50)),
                ('star_annotation', models.CharField(max_length=50)),
                ('allele', models.CharField(max_length=50)),
                ('phenotype', models.TextField(default='NA')),
                ('p_value', models.CharField(max_length=20, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('id_in_source', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(default='Undetermined', max_length=50)),
                ('country_of_participants', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('drug', models.ForeignKey(default='DRUG0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug')),
                ('gene', models.ForeignKey(default='GENE0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study')),
            ],
        ),
        migrations.CreateModel(
            name='snp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('snp_id', models.CharField(default='NA', max_length=50)),
                ('rs_id', models.CharField(default='RS0', max_length=50)),
                ('allele', models.CharField(max_length=50)),
                ('association_with', models.TextField(default='NA')),
                ('p_value', models.CharField(max_length=10, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('id_in_source', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(default='Undetermined', max_length=50)),
                ('country_of_participants', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('drug', models.ForeignKey(default='DRUG0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug')),
                ('gene', models.ForeignKey(default='GENE0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study')),
            ],
        ),
    ]
