# Generated by Django 2.2.24 on 2023-01-31 10:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Country Population Data',
            },
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.CharField(default='DIS0', max_length=50, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.CharField(default='DRUG0', max_length=50, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=250)),
                ('drug_bank_id', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
                ('indication', models.TextField()),
                ('iupac_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drugagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_bank_id', models.CharField(blank=True, max_length=50, null=True)),
                ('drug_name', models.CharField(blank=True, max_length=50, null=True)),
                ('indication', models.TextField(blank=True, max_length=50, null=True)),
                ('iupac_name_seq', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '* Drugs',
            },
        ),
        migrations.CreateModel(
            name='Geneagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=50, null=True)),
                ('function', models.TextField(blank=True, max_length=50, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=50, null=True)),
                ('uniprot_ac', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '* Gene',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recname', models.CharField(max_length=250)),
                ('keywords', models.CharField(default='NA', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacogenes',
            fields=[
                ('id', models.CharField(default='GENE0', max_length=50, primary_key=True, serialize=False)),
                ('chromosome_patch', models.CharField(default='NA', max_length=50)),
                ('gene_name', models.CharField(default='NA', max_length=50)),
                ('uniprot_id', models.CharField(max_length=50, null=True)),
                ('function', models.TextField(default='NA', max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pharmacogenes',
            },
        ),
        migrations.CreateModel(
            name='Phenotypeagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '* Phenotype',
            },
        ),
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=250)),
                ('year', models.CharField(default='NA', max_length=10)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='Studyagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ac', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_id', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_type', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_year', models.CharField(blank=True, max_length=50, null=True)),
                ('study_type', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '* Studies',
            },
        ),
        migrations.CreateModel(
            name='Variantagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(blank=True, max_length=50, null=True)),
                ('source_db', models.CharField(blank=True, max_length=50, null=True)),
                ('id_in_source_db', models.CharField(blank=True, max_length=50, null=True)),
                ('rs_id_star_annotation', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_type', models.CharField(blank=True, max_length=50, null=True)),
                ('drugagmp', models.ForeignKey(blank=True, default='DRUG', null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Drugagmp')),
                ('geneagmp', models.ForeignKey(blank=True, default='GENE', null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Geneagmp')),
                ('phenotypeagmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Phenotypeagmp')),
                ('studyagmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Studyagmp')),
            ],
            options={
                'verbose_name_plural': '* Variant',
            },
        ),
        migrations.CreateModel(
            name='VariantStudyagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_participant', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('geographical_regions', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('p_value', models.CharField(blank=True, max_length=50, null=True)),
                ('studyagmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Studyagmp')),
                ('variantagmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Variantagmp')),
            ],
            options={
                'verbose_name_plural': '* Variant Studies',
            },
        ),
        migrations.CreateModel(
            name='star_allele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_id', models.CharField(default='NA', max_length=50)),
                ('star_annotation', models.CharField(max_length=50)),
                ('allele', models.CharField(max_length=50)),
                ('phenotype', models.TextField(default='NA')),
                ('p_value', models.CharField(max_length=20, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('id_in_source', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(default='Undetermined', max_length=50)),
                ('country_of_participants', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('drug', models.ForeignKey(default='DRUG0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug')),
                ('gene', models.ForeignKey(default='GENE0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study')),
            ],
            options={
                'verbose_name_plural': 'Star alleles',
            },
        ),
        migrations.CreateModel(
            name='snp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('snp_id', models.CharField(default='NA', max_length=50)),
                ('rs_id', models.CharField(default='RS0', max_length=50)),
                ('allele', models.CharField(max_length=50)),
                ('association_with', models.TextField(default='NA')),
                ('p_value', models.CharField(max_length=10, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('id_in_source', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(default='Undetermined', max_length=50)),
                ('country_of_participants', models.CharField(max_length=50, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('disease', models.ForeignKey(default='DIS0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.disease')),
                ('drug', models.ForeignKey(default='DRUG0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.drug')),
                ('gene', models.ForeignKey(default='GENE0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.pharmacogenes')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.study')),
            ],
            options={
                'verbose_name_plural': 'SNPs',
            },
        ),
    ]
