# Generated by Django 2.2.13 on 2021-10-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('drug_bank_id', models.CharField(max_length=50, null=True)),
                ('drug_name', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250, null=True)),
                ('indication', models.TextField()),
                ('iupac_name_or_sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(default='NA', max_length=50)),
                ('uniprot_ac', models.CharField(max_length=50, null=True)),
                ('function', models.TextField(default='NA', max_length=2500, null=True)),
                ('chromosome', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('publication_id', models.CharField(default='NA', max_length=50)),
                ('publication_type', models.CharField(max_length=50, null=True)),
                ('publication_year', models.CharField(default='NA', max_length=50, null=True)),
                ('title', models.CharField(default='NA', max_length=250)),
                ('study_type', models.CharField(default='NA', max_length=50)),
                ('data_ac', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=50)),
                ('rs_id_star_annotation', models.CharField(max_length=50)),
                ('variant_type', models.CharField(max_length=50)),
                ('allele', models.CharField(max_length=50)),
                ('clinical_significance', models.CharField(blank=True, max_length=50, null=True)),
                ('clinvar_variation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source_db', models.CharField(max_length=50)),
                ('id_in_source_db', models.CharField(max_length=50)),
                ('drugs', models.ManyToManyField(to='agmp_app.Drug')),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Variant_Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(null=True)),
                ('p_value_is_exact', models.BooleanField(default=True)),
                ('country_of_participants', models.CharField(default='NA', max_length=50, null=True)),
                ('geographical_regions', models.CharField(default='NA', max_length=50, null=True)),
                ('ethnicity', models.CharField(default='NA', max_length=50, null=True)),
                ('notes', models.TextField(default='NA', max_length=2500, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Study')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agmp_app.Variant')),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='variants',
            field=models.ManyToManyField(through='agmp_app.Variant_Study', to='agmp_app.Variant'),
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('phenotype_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('variants', models.ManyToManyField(to='agmp_app.Variant')),
            ],
        ),
    ]
