# Generated by Django 2.2.24 on 2023-03-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantagmp',
            name='drugagmp',
            field=models.ForeignKey(blank=True, default='DRUG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugv', to='agmp_app.Drugagmp'),
        ),
    ]
