# Generated by Django 2.2.1 on 2019-10-27 09:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp_ethnicity_country',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10),
        ),
        migrations.AddField(
            model_name='snp_ethnicity_country',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10),
        ),
        migrations.AddField(
            model_name='star_allele_ethnicity_country',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10),
        ),
        migrations.AddField(
            model_name='star_allele_ethnicity_country',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='snp_ethnicity_country',
            name='snp',
            field=models.CharField(max_length=50),
        ),
    ]
