# Generated by Django 2.2.13 on 2021-10-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.CharField(default='DIS0', max_length=50, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='snp',
            name='disease',
            field=models.ForeignKey(default='DIS0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.disease'),
        ),
    ]
