# Generated by Django 2.2.24 on 2023-02-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantagmp',
            name='rs_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
