# Generated by Django 3.2.23 on 2023-12-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StaffModel',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='StudentModel',
        ),
        migrations.RenameField(
            model_name='staffmodel',
            old_name='student_id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='staff_id',
            new_name='student_id',
        ),
    ]
