# Generated by Django 2.2.1 on 2020-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0002_auto_20191027_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('recname', models.CharField(max_length=250)),
                ('keywords', models.CharField(default='NA', max_length=250)),
            ],
        ),
    ]
