# Generated by Django 2.2.24 on 2022-05-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0002_auto_20220513_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.CharField(default='DIS0', max_length=50, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='star_allele',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='snp',
            name='disease',
            field=models.ForeignKey(default='DIS0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.disease'),
        ),
    ]
