# Generated by Django 3.2.23 on 2024-06-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0003_auto_20240606_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='star_allele',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='star_allele',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='star_allele',
            name='reference',
        ),
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='drug',
        ),
        migrations.DeleteModel(
            name='pharmacogenes',
        ),
        migrations.DeleteModel(
            name='snp',
        ),
        migrations.DeleteModel(
            name='star_allele',
        ),
        migrations.DeleteModel(
            name='study',
        ),
    ]
