# Generated by Django 2.2.24 on 2022-08-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0003_auto_20220513_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.CharField(default='DIS0', max_length=50, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pharmacogenes',
            options={'verbose_name_plural': 'Pharmacogenes'},
        ),
        migrations.AlterModelOptions(
            name='snp',
            options={'verbose_name_plural': 'SNPs'},
        ),
        migrations.AlterModelOptions(
            name='star_allele',
            options={'verbose_name_plural': 'Star alleles'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.AlterField(
            model_name='star_allele',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='snp',
            name='disease',
            field=models.ForeignKey(default='DIS0', on_delete=django.db.models.deletion.CASCADE, to='agmp_app.disease'),
        ),
    ]
