# Generated by Django 2.2.24 on 2023-01-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0003_variantstudyagmp_studyagmp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='ethnicity',
            new_name='Ethnicity',
        ),
    ]
