# Generated by Django 2.2.24 on 2023-05-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0003_book_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
