# Generated by Django 3.2.23 on 2024-06-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0004_auto_20240620_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugagmp',
            options={'verbose_name_plural': 'Drugs'},
        ),
        migrations.AlterModelOptions(
            name='geneagmp',
            options={'verbose_name_plural': 'Gene'},
        ),
        migrations.AlterModelOptions(
            name='phenotypeagmp',
            options={'verbose_name_plural': 'Phenotype'},
        ),
        migrations.AlterModelOptions(
            name='studyagmp',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.AlterModelOptions(
            name='variantagmp',
            options={'verbose_name_plural': ' Variant'},
        ),
        migrations.AlterModelOptions(
            name='variantstudyagmp',
            options={'verbose_name_plural': ' Variant Studies'},
        ),
    ]
