# Generated by Django 2.2.24 on 2023-07-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0004_auto_20230508_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantagmp',
            name='drugagmp',
            field=models.ForeignKey(blank=True, default='DRUG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='agmp_app.Drugagmp'),
        ),
        migrations.AlterField(
            model_name='variantagmp',
            name='studyagmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studys', to='agmp_app.Studyagmp'),
        ),
    ]
