# Generated by Django 2.2.24 on 2023-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0004_auto_20230117_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugagmp',
            options={'verbose_name_plural': '* Drugs'},
        ),
        migrations.AlterModelOptions(
            name='geneagmp',
            options={'verbose_name_plural': '* Gene'},
        ),
        migrations.AlterModelOptions(
            name='phenotypeagmp',
            options={'verbose_name_plural': '* Phenotype'},
        ),
        migrations.AlterModelOptions(
            name='studyagmp',
            options={'verbose_name_plural': '* Studies'},
        ),
        migrations.AlterModelOptions(
            name='variantagmp',
            options={'verbose_name_plural': '* Variant'},
        ),
        migrations.AlterModelOptions(
            name='variantstudyagmp',
            options={'verbose_name_plural': '* Variant Studies'},
        ),
        migrations.AlterField(
            model_name='variantstudyagmp',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
