# Generated by Django 2.2.24 on 2023-01-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0005_auto_20230117_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyagmp',
            name='study_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
