# Generated by Django 3.2.25 on 2024-09-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0005_auto_20240626_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantagmp',
            name='drugagmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='agmp_app.drugagmp'),
        ),
    ]
