# Generated by Django 3.2.22 on 2023-11-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0005_drugagmp_geneagmp_phenotypeagmp_studyagmp_variantagmp_variantstudyagmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryData',
        ),
    ]
