# Generated by Django 3.2.25 on 2024-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0006_alter_variantagmp_drugagmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstudyagmp',
            name='mixed_population',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
