# Generated by Django 2.2.24 on 2023-01-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0007_auto_20230118_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypeagmp',
            name='name',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
