# Generated by Django 4.2.19 on 2025-03-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0008_alter_drugagmp_drug_bank_id_alter_drugagmp_drug_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenotypeSubmissionagmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcid_id', models.CharField(blank=True, max_length=500, null=True)),
                ('pmid_id', models.CharField(blank=True, max_length=500, null=True)),
                ('phenotype_of_interest', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
