# Generated by Django 4.2.20 on 2025-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0008_alter_drugagmp_drug_bank_id_alter_drugagmp_drug_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinPhenData',
            fields=[
                ('phenotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_class', models.CharField(max_length=45)),
                ('hpo_class', models.CharField(max_length=45)),
                ('who_class', models.CharField(max_length=45)),
                ('curated_data', models.CharField(max_length=45)),
                ('comorbidities', models.CharField(max_length=45)),
                ('symptoms', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Clinical Phenotype Data',
            },
        ),
        migrations.CreateModel(
            name='DataBaseClinicalSig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clin_sign', models.CharField(max_length=45)),
                ('database_link', models.CharField(max_length=45)),
                ('func_pred_toolname', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Database Clinical Significances',
            },
        ),
        migrations.AddField(
            model_name='variantagmp',
            name='clin_phen_data',
            field=models.ManyToManyField(blank=True, to='agmp_app.clinphendata'),
        ),
        migrations.AddField(
            model_name='variantagmp',
            name='database_clinical_sig',
            field=models.ManyToManyField(blank=True, to='agmp_app.databaseclinicalsig'),
        ),
    ]
