# Generated by Django 4.2.19 on 2025-03-02 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0009_phenotypesubmissionagmp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phenotypesubmissionagmp',
            options={'verbose_name_plural': 'Phenotype Submissions'},
        ),
        migrations.AddField(
            model_name='phenotypesubmissionagmp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
