# Generated by Django 4.2.20 on 2025-06-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0009_clinphendata_databaseclinicalsig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantagmp',
            name='clin_phen_data',
        ),
        migrations.RemoveField(
            model_name='variantagmp',
            name='database_clinical_sig',
        ),
        migrations.DeleteModel(
            name='ClinPhenData',
        ),
        migrations.DeleteModel(
            name='DataBaseClinicalSig',
        ),
    ]
