# Generated by Django 3.2.22 on 2023-11-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0009_modelc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelc',
            old_name='title',
            new_name='description',
        ),
    ]
