# Generated by Django 3.2.22 on 2023-11-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0010_rename_title_modelc_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelb',
            old_name='title',
            new_name='name',
        ),
    ]
