# Generated by Django 4.2.19 on 2025-03-07 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agmp_app", "0010_alter_phenotypesubmissionagmp_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phenotypesubmissionagmp",
            options={},
        ),
        migrations.AlterField(
            model_name="phenotypesubmissionagmp",
            name="orcid_id",
            field=models.CharField(
                blank=True,
                help_text='Format: XXXX-XXXX-XXXX-XXXX (X can be a digit or "X").',
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Enter a valid ORCID ID. Format: XXXX-XXXX-XXXX-XXXX (X can be a digit or "X").',
                        regex="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$",
                    )
                ],
            ),
        ),
    ]
