# Generated by Django 4.2.20 on 2025-09-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0010_remove_variantagmp_clin_phen_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='latitude_10',
            new_name='latitude_010',
        ),
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='latitude_11',
            new_name='latitude_011',
        ),
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='longitude_10',
            new_name='longitude_010',
        ),
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='longitude_11',
            new_name='longitude_011',
        ),
    ]
