# Generated by Django 3.2.22 on 2023-11-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0011_rename_title_modelb_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelb',
            old_name='name',
            new_name='title',
        ),
    ]
