# Generated by Django 4.2.20 on 2025-09-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0011_rename_latitude_10_variantstudyagmp_latitude_010_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='latitude_010',
            new_name='latitude_10',
        ),
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='latitude_011',
            new_name='latitude_11',
        ),
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='longitude_010',
            new_name='longitude_10',
        ),
        migrations.RenameField(
            model_name='variantstudyagmp',
            old_name='longitude_011',
            new_name='longitude_11',
        ),
    ]
