# Generated by Django 4.2.19 on 2025-03-07 22:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("agmp_app", "0011_alter_phenotypesubmissionagmp_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phenotypesubmissionagmp",
            options={"verbose_name_plural": "Phenotype Submissions"},
        ),
        migrations.AlterField(
            model_name="phenotypesubmissionagmp",
            name="orcid_id",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Enter a valid ORCID ID. Format: XXXX-XXXX-XXXX-XXXX (X can be a digit or "X").',
                        regex="^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
