# Generated by Django 4.2.25 on 2025-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0012_rename_latitude_010_variantstudyagmp_latitude_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_012',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_013',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_014',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_015',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_016',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_017',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_018',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_019',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_20',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_21',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_22',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_23',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_24',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_25',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_26',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_27',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_28',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_29',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_30',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_14',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_15',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_16',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_17',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_18',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_19',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_20',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_21',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_22',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_23',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_24',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_25',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_26',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_27',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_28',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_29',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_30',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_14',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_15',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_16',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_17',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_18',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_19',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_20',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_21',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_22',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_23',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_24',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_25',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_26',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_27',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_28',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_29',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_30',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
