# Generated by Django 3.2.22 on 2023-11-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0012_rename_name_modelb_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelC',
            new_name='Item',
        ),
    ]
