# Generated by Django 3.2.22 on 2023-11-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0013_rename_modelc_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='name',
        ),
    ]
