# Generated by Django 5.2.10 on 2026-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0013_variantstudyagmp_country_participant_012_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ols_id', models.CharField(help_text="OLS4 ontology identifier, e.g. 'doid', 'hp', 'mondo', 'chebi'", max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('phenotype', 'Phenotype / Disease'), ('drug', 'Drug / Chemical'), ('gene', 'Gene / Protein'), ('variant', 'Variant')], db_index=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = searched first')),
                ('expand_children', models.BooleanField(default=True, help_text='Include child terms in search expansion')),
                ('child_depth', models.PositiveIntegerField(default=1, help_text='How many levels of children to walk')),
                ('max_search_hits', models.PositiveIntegerField(default=5, help_text='Max OLS results to process per query')),
                ('max_children', models.PositiveIntegerField(default=30, help_text='Max child terms to fetch per hit')),
                ('cache_duration', models.PositiveIntegerField(default=86400, help_text='Cache TTL in seconds (default 24h)')),
            ],
            options={
                'verbose_name': 'Ontology Source',
                'ordering': ['category', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='OxOMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_category', models.CharField(choices=[('phenotype', 'Phenotype / Disease'), ('drug', 'Drug / Chemical'), ('gene', 'Gene / Protein'), ('variant', 'Variant')], max_length=20)),
                ('target_ontology_prefix', models.CharField(help_text="OxO target prefix, e.g. 'MONDO', 'HP', 'EFO'", max_length=50)),
                ('distance', models.PositiveIntegerField(default=2, help_text='Max mapping hops in OxO')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['source_category', 'target_ontology_prefix'],
            },
        ),
        migrations.CreateModel(
            name='SearchFieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('phenotype', 'Phenotype / Disease'), ('drug', 'Drug / Chemical'), ('gene', 'Gene / Protein'), ('variant', 'Variant')], max_length=20)),
                ('lookup_field', models.CharField(help_text="Django ORM field path, e.g. 'phenotypeagmp__name' or 'drug_name'", max_length=200)),
                ('lookup_type', models.CharField(default='iexact', help_text='Django lookup: iexact, icontains, exact, etc.', max_length=20)),
                ('is_fallback', models.BooleanField(default=False, help_text='If True, this mapping is used as a loose fallback (icontains on raw input)')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Search Field Mapping',
                'ordering': ['category', 'is_fallback'],
            },
        ),
    ]
