from django.db import models
from decimal import Decimal
import geocoder
from django.urls import reverse

#====New Models=======#
from django.db import models


#Drug ids
def increment_drug_id():
    last_drug_id = Drugagmp.objects.all().order_by('id').last()
    if not last_drug_id:
        return 'DRUG001'
    drug_id = last_drug_id.drug_id
    width = 3
    drug_id_int = int(drug_id.split('DRUG')[-1])
    new_drug_id_int = drug_id_int + 1
    formatted = (width - len(str(new_drug_id_int))) * \
        "0" + str(new_drug_id_int)
    new_drug_id = 'DRUG' + str(formatted)
    return new_drug_id

######### New Models #############
class Drugagmp(models.Model):
    # drug_id = models.CharField(max_length=50, null=True, blank=True)
    drug_bank_id = models.CharField(max_length=1500, null=True, blank=True)
    drug_name = models.CharField(max_length=1500, null=True, blank=True)
    indication = models.TextField(max_length=1500, null=True, blank=True)
    iupac_name_seq = models.CharField(max_length=1500, null=True, blank=True)
    state = models.CharField(max_length=1500, null=True, blank=True)
    # will be autogenerated on save
    drug_id = models.CharField(
        max_length=255, default=increment_drug_id, null=True, blank=True)
    class Meta:
        verbose_name_plural = "Drugs"
        
    def __str__(self):
        return f"{self.drug_bank_id}"

class Geneagmp(models.Model):
     # will be autogenerated on save
    gene_id = models.CharField(max_length=1500, null=True, blank=True)
    # gene_id =models.UUIDField(primary_key=True, default= uuid.uuid4,editable=False)
    chromosome = models.CharField(max_length=1500, null=True, blank=True)
    function = models.TextField(max_length=1500, null=True, blank=True)
    gene_name= models.CharField(max_length=1500, null=True, blank=True)
    uniprot_ac= models.CharField(max_length=1500, null=True, blank=True)
 
    class Meta:
        verbose_name_plural = "Gene"

    def __str__(self):
        return f"{self.gene_id}"

class Studyagmp(models.Model):
    data_ac = models.CharField(max_length=1500, null=True, blank=True)
    publication_id = models.CharField(max_length=1500, null=True, blank=True)
    publication_type = models.CharField(max_length=1500, null=True, blank=True)
    publication_year = models.CharField(max_length=50, null=True, blank=True)
    study_type = models.CharField(max_length=1500, null=True, blank=True)
    title = models.TextField(max_length=1500, null=True, blank=True)
    class Meta:
        verbose_name_plural = "Studies"

class Phenotypeagmp(models.Model): # will be the diseases
    name = models.TextField(max_length=1500, null=True, blank=True)
    class Meta:
        verbose_name_plural = "Phenotype"
   
class Variantagmp(models.Model):
    geneagmp = models.ForeignKey(Geneagmp, on_delete=models.CASCADE, default="GENE",null=True, blank=True)
    allele = models.CharField(max_length=1500, null=True, blank=True)
    drugagmp = models.ForeignKey(
    Drugagmp, 
    on_delete=models.SET_NULL,
    related_name="drugs", 
    null=True, 
    blank=True
)
    #drugagmp = models.ForeignKey(Drugagmp, on_delete=models.CASCADE, related_name="drugs", default="DRUG",null=True, blank=True)
    source_db = models.CharField(max_length=1500, null=True, blank=True)
    studyagmp = models.ForeignKey(Studyagmp, on_delete=models.CASCADE, related_name="studys",null=True, blank=True)
    phenotypeagmp = models.ForeignKey(Phenotypeagmp, on_delete=models.CASCADE,null=True, blank=True)
    # extra models
    id_in_source_db = models.CharField(max_length=1500, null=True, blank=True)
    rs_id_star_annotation = models.CharField(max_length=1500, null=True, blank=True) #which column is this in the csv file?
    variant_type = models.CharField(max_length=1500, null=True, blank=True)
    rs_id = models.CharField(max_length=1500, null=True, blank=True)
    class Meta:
        verbose_name_plural = " Variant"

class VariantStudyagmp(models.Model):
    variantagmp = models.ForeignKey(Variantagmp, on_delete=models.CASCADE,null=True, blank=True)
    studyagmp = models.ForeignKey(Studyagmp, on_delete=models.CASCADE,null=True, blank=True)
    #country participant
    country_participant = models.CharField(max_length=1500, null=True, blank=True)
    latitude = models.CharField(max_length=500, null=True, blank=True)
    longitude = models.CharField(max_length=500, null=True, blank=True)
     #country participant
    country_participant_01 = models.CharField(max_length=500, null=True, blank=True)
    latitude_01 = models.CharField(max_length=500, null=True, blank=True)
    longitude_01 = models.CharField(max_length=500, null=True, blank=True)
     #country participant
    country_participant_02 = models.CharField(max_length=500, null=True, blank=True)
    latitude_02 = models.CharField(max_length=500, null=True, blank=True)
    longitude_02 = models.CharField(max_length=500, null=True, blank=True)
     #country participant
    #country participant
    country_participant_03 = models.CharField(max_length=500, null=True, blank=True)
    latitude_03 = models.CharField(max_length=500, null=True, blank=True)
    longitude_03 = models.CharField(max_length=500, null=True, blank=True)
    #country participant
    country_participant_04 = models.CharField(max_length=500, null=True, blank=True)
    latitude_04 = models.CharField(max_length=500, null=True, blank=True)
    longitude_04 = models.CharField(max_length=500, null=True, blank=True)
     #country participant
    country_participant_05 = models.CharField(max_length=500, null=True, blank=True)
    latitude_05 = models.CharField(max_length=500, null=True, blank=True)
    longitude_05 = models.CharField(max_length=500, null=True, blank=True)
     #country participant
    country_participant_06 = models.CharField(max_length=500, null=True, blank=True)
    latitude_06 = models.CharField(max_length=500, null=True, blank=True)
    longitude_06 = models.CharField(max_length=500, null=True, blank=True)
     #country participant
    country_participant_07 = models.CharField(max_length=500, null=True, blank=True)
    latitude_07 = models.CharField(max_length=500, null=True, blank=True)
    longitude_07 = models.CharField(max_length=500, null=True, blank=True)
     #country participant

    country_participant_08 = models.CharField(max_length=500, null=True, blank=True)
    latitude_08 = models.CharField(max_length=500, null=True, blank=True)
    longitude_08 = models.CharField(max_length=500, null=True, blank=True)
     #country participant

    country_participant_09 = models.CharField(max_length=500, null=True, blank=True)
    latitude_09 = models.CharField(max_length=500, null=True, blank=True)
    longitude_09 = models.CharField(max_length=500, null=True, blank=True)
     #country participant

    country_participant_010 = models.CharField(max_length=500, null=True, blank=True)
    latitude_10 = models.CharField(max_length=500, null=True, blank=True)
    longitude_10 = models.CharField(max_length=500, null=True, blank=True)
    #country participant

    country_participant_011 = models.CharField(max_length=500, null=True, blank=True)
    latitude_11 = models.CharField(max_length=500, null=True, blank=True)
    longitude_11 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_012 = models.CharField(max_length=500, null=True, blank=True)
    latitude_12 = models.CharField(max_length=500, null=True, blank=True)
    longitude_12 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_013 = models.CharField(max_length=500, null=True, blank=True)
    latitude_13 = models.CharField(max_length=500, null=True, blank=True)
    longitude_13 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_014 = models.CharField(max_length=500, null=True, blank=True)
    latitude_14 = models.CharField(max_length=500, null=True, blank=True)
    longitude_14 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_015 = models.CharField(max_length=500, null=True, blank=True)
    latitude_15 = models.CharField(max_length=500, null=True, blank=True)
    longitude_15 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_016 = models.CharField(max_length=500, null=True, blank=True)
    latitude_16 = models.CharField(max_length=500, null=True, blank=True)
    longitude_16 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_017 = models.CharField(max_length=500, null=True, blank=True)
    latitude_17 = models.CharField(max_length=500, null=True, blank=True)
    longitude_17 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_018 = models.CharField(max_length=500, null=True, blank=True)
    latitude_18 = models.CharField(max_length=500, null=True, blank=True)
    longitude_18 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_019 = models.CharField(max_length=500, null=True, blank=True)
    latitude_19 = models.CharField(max_length=500, null=True, blank=True)
    longitude_19 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_20 = models.CharField(max_length=500, null=True, blank=True)
    latitude_20 = models.CharField(max_length=500, null=True, blank=True)
    longitude_20 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_21 = models.CharField(max_length=500, null=True, blank=True)
    latitude_21 = models.CharField(max_length=500, null=True, blank=True)
    longitude_21 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_22 = models.CharField(max_length=500, null=True, blank=True)
    latitude_22 = models.CharField(max_length=500, null=True, blank=True)
    longitude_22 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_23 = models.CharField(max_length=500, null=True, blank=True)
    latitude_23 = models.CharField(max_length=500, null=True, blank=True)
    longitude_23 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_24 = models.CharField(max_length=500, null=True, blank=True)
    latitude_24 = models.CharField(max_length=500, null=True, blank=True)
    longitude_24 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_25 = models.CharField(max_length=500, null=True, blank=True)
    latitude_25 = models.CharField(max_length=500, null=True, blank=True)
    longitude_25 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_26 = models.CharField(max_length=500, null=True, blank=True)
    latitude_26 = models.CharField(max_length=500, null=True, blank=True)
    longitude_26 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_27 = models.CharField(max_length=500, null=True, blank=True)
    latitude_27 = models.CharField(max_length=500, null=True, blank=True)
    longitude_27 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_28 = models.CharField(max_length=500, null=True, blank=True)
    latitude_28 = models.CharField(max_length=500, null=True, blank=True)
    longitude_28 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_29 = models.CharField(max_length=500, null=True, blank=True)
    latitude_29 = models.CharField(max_length=500, null=True, blank=True)
    longitude_29 = models.CharField(max_length=500, null=True, blank=True)

    country_participant_30 = models.CharField(max_length=500, null=True, blank=True)
    latitude_30 = models.CharField(max_length=500, null=True, blank=True)
    longitude_30 = models.CharField(max_length=500, null=True, blank=True)


    mixed_population = models.CharField(max_length=8, null=True, blank=True)
    ethnicity = models.CharField(max_length=500, null=True, blank=True)
    geographical_regions = models.CharField(max_length=500, null=True, blank=True)
    notes = models.TextField(max_length=500, null=True, blank=True)
    p_value = models.CharField(max_length=500, null=True, blank=True)


    class Meta:
        verbose_name_plural = " Variant Studies"
#====New Models=======#

class OntologyConfig(models.Model):
    """
    Admin-configurable ontology source.
    Add/remove ontologies without touching code.
    """
    ols_id = models.CharField(
        max_length=50, unique=True,
        help_text="OLS4 ontology identifier, e.g. 'doid', 'hp', 'mondo', 'chebi'"
    )
    display_name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    CATEGORY_CHOICES = [
        ('phenotype', 'Phenotype / Disease'),
        ('drug', 'Drug / Chemical'),
        ('gene', 'Gene / Protein'),
        ('variant', 'Variant'),
    ]
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, db_index=True)
    enabled = models.BooleanField(default=True)
    priority = models.PositiveIntegerField(
        default=10,
        help_text="Lower number = searched first"
    )
    expand_children = models.BooleanField(
        default=True,
        help_text="Include child terms in search expansion"
    )
    child_depth = models.PositiveIntegerField(
        default=1,
        help_text="How many levels of children to walk"
    )
    max_search_hits = models.PositiveIntegerField(
        default=5,
        help_text="Max OLS results to process per query"
    )
    max_children = models.PositiveIntegerField(
        default=30,
        help_text="Max child terms to fetch per hit"
    )
    cache_duration = models.PositiveIntegerField(
        default=86400,
        help_text="Cache TTL in seconds (default 24h)"
    )

    class Meta:
        ordering = ['category', 'priority']
        verbose_name = 'Ontology Source'

    def __str__(self):
        state = '✓' if self.enabled else '✗'
        return f"[{state}] {self.display_name} ({self.ols_id}) — {self.get_category_display()}"


class SearchFieldMapping(models.Model):
    """
    Maps a search category to the Django ORM lookup field.
    Allows admin to change which model fields are matched
    without editing views.
    """
    CATEGORY_CHOICES = OntologyConfig.CATEGORY_CHOICES

    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    lookup_field = models.CharField(
        max_length=200,
        help_text="Django ORM field path, e.g. 'phenotypeagmp__name' or 'drug_name'"
    )
    lookup_type = models.CharField(
        max_length=20, default='iexact',
        help_text="Django lookup: iexact, icontains, exact, etc."
    )
    is_fallback = models.BooleanField(
        default=False,
        help_text="If True, this mapping is used as a loose fallback (icontains on raw input)"
    )
    enabled = models.BooleanField(default=True)

    class Meta:
        ordering = ['category', 'is_fallback']
        verbose_name = 'Search Field Mapping'

    def __str__(self):
        fb = ' (fallback)' if self.is_fallback else ''
        return f"{self.get_category_display()}: {self.lookup_field}__{self.lookup_type}{fb}"

########################### Ontology Mapping ############################
class OxOMapping(models.Model):
    """
    Optional cross-ontology mapping config.
    Only used when you need to bridge between ontology vocabularies.
    """
    source_category = models.CharField(max_length=20, choices=OntologyConfig.CATEGORY_CHOICES)
    target_ontology_prefix = models.CharField(
        max_length=50,
        help_text="OxO target prefix, e.g. 'MONDO', 'HP', 'EFO'"
    )
    distance = models.PositiveIntegerField(
        default=2,
        help_text="Max mapping hops in OxO"
    )
    enabled = models.BooleanField(default=True)

    class Meta:
        ordering = ['source_category', 'target_ontology_prefix']

    def __str__(self):
        return f"{self.source_category} → {self.target_ontology_prefix} (dist {self.distance})"

