# Generated by Django 3.2.18 on 2023-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agmp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstudyagmp',
            name='country_participant_07',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='latitude_07',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='variantstudyagmp',
            name='longitude_07',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
